### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Devon7925** [WearBlackAllDay/DimensionalThreading#1]
See log attached
[crash-2020-09-25_18.21.28-server.txt](https://github.com/WearBlackAllDay/DimensionalThreading/files/5284645/crash-2020-09-25_18.21.28-server.txt)

**Comment by WearBlackAllDay** [comment]
@Devon7925 I am sorry to only just see this, i did not expect to run into an issue report that quickly; however i am always happy to receive more data to improve the mod on.
Concerning your crash, did you happen to use an outdated build?

**Comment by Devon7925** [comment]
I don't think so. I used the 1.0 release. I tried both the dev and non dev version and neither seemed to work

**Comment by Devon7925** [comment]
One thing that probably matters is that I was using a datapack with custom dimensions

**Comment by Devon7925** [comment]
@WearBlackAllDay I think the problem is herehttps://github.com/WearBlackAllDay/DimensionalThreading/blob/03aec22a2c76f1147a16ce9417fad65251ce3ad4/src/main/java/dimthread/mixin/MinecraftServerMixin.java#L69. This fails if the dimension count is not 3. If you want I can send you a sample datapack that adds dimensions.

**Comment by WearBlackAllDay** [comment]
Yep, thats exactly it
until there is a proper fix the solution for now would be manually adjusting the threadcount with an ingame command.

**Comment by Devon7925** [comment]
1. Increacing the threadcount doesn't fix this, that line needs to be changed
2. An ingame command cant be run if you can't load the world

**Comment by KaptainWutax** [comment]
Kinda yoloed that since I was too lazy to write a datapack. It should do it hopefully. :p
