### ISSUE TITLE
Bug with Tic-Tacs

### ISSUE THREAD

**Issue by QPCrummer** [WearBlackAllDay/DimensionalThreading#12]
It allows for duplication of items and blocks!
https://github.com/Gegy/tic-tacs/issues/29

**Comment by KaptainWutax** [comment]
Is there a mixin conflict?

**Comment by SnooComics9452** [comment]
y i think should close this issue

**Comment by DragonEggBedrockBreaking** [comment]
cannot reproduce issue (noted already on tic tacs issue report)
(ik this is closed, I was just mentioning)
