### ISSUE TITLE
Carpet + fabric api + dimensional threading with the command /spawn tracking start causes crash

### ISSUE THREAD

**Issue by JonasStorm** [WearBlackAllDay/DimensionalThreading#13]
https://paste.ee/p/W7zzk

**Comment by JonasStorm** [comment]
Special thanks to the mod Not Enough Crashes for helping me figure this out

**Comment by JonasStorm** [comment]
[crash-2021-01-11_16.01.12-server.txt](https://github.com/WearBlackAllDay/DimensionalThreading/files/5798999/crash-2021-01-11_16.01.12-server.txt)

**Comment by KaptainWutax** [comment]
Profiling commands in general can't function properly since dimensions are running asynchronously. Not much that can be done on the dimthread side sorry.
