### ISSUE TITLE
Crash when trying to use debug command

### ISSUE THREAD

**Issue by Devon7925** [WearBlackAllDay/DimensionalThreading#2]
See log here: https://pastebin.com/cGvjHhj0. Crash upon entering command /debug start

**Comment by KaptainWutax** [comment]
I am aware of this problem but there's just no way to fix that without rewriting the entire vanilla profiler. It's just not built to be thread-safe.

**Comment by Devon7925** [comment]
I was trying to use the debug command to determine the cause of other issues, I'm still getting crashes unrelated to this, but this was the only crash I could consistently reproduce. It would help if you would at least disable the debug command or override it with a simpler version that only shows mspt and tps.

**Comment by KaptainWutax** [comment]
If you want to see tps and mspt you should use carpetmod by gnembon.

**Comment by Devon7925** [comment]
I already have carpet mod on my server, but I cant put this mod on my server because it's too unstable. I was using the debug command to try to determine why it is unstable but failed because I cant use it.

**Comment by whoImT** [comment]
for me it worked when I was using carpetmod and it was stable

**Comment by Devon7925** [comment]
My instability problem was #4, which I guess most people wouldn't encounter
