### ISSUE TITLE
No /gamerules for DimThread exists after installing on the server

### ISSUE THREAD

**Issue by Greg-J** [WearBlackAllDay/DimensionalThreading#27]
Fabric 1.17 server on Ubuntu 20.04 running Java 16. This server runs in an LXC container on Proxmox and has 4 cores and 12GB of RAM allocated to it.

I am using the CavesAndCliffsPreview.zip datapack if that matters.

I have DimThread installed on the server. It shows up in the startup log as being a loaded mod. However, there is no gamerule for it and trying to execute `/gamerule dimthread_active true` results in `Incorrect argument for command`.

A list of mods the server is running:

- carpet-extra-1.17-1.4.40.jar
- DimThread-1.2.4.jar
- fabric-api-0.35.0+1.17.jar
- fabric-carpet-1.17-1.4.40+v210608.jar
- Fabric-Discord-Link-0.9.4.jar
- krypton-0.1.3.jar
- lithium-fabric-mc1.17-0.7.0.jar
- mostructures-1.2.0-pre2+mc.1.17.jar
- worldedit-fabric-mc1.17-7.2.6-SNAPSHOT-dist.jar

**Comment by pooky125** [comment]
I'm also having this issue. Fabric 1.17 server, 16 gigs of ram, using 1 core. I'm not using the CavesAndCliffs datapack, but the gamerules are also not populating for me with the same result as Greg-J.

The mods I'm using are
BlueMap-1.53.0-1.17.jar
fabric-api-0.34.10_+1.17.jar
Fabric-Discord-Link-0.9.4.jar
fdlink-api-0.1.0.jar
lithium-fabric-mc1.17-0.7.0.jar
starlight-fabric-1.0.0-RC2-1.17.x.jar

**Comment by WearBlackAllDay** [comment]
fixed in new release
