### ISSUE TITLE
Is this a normal phenomenon?

### ISSUE THREAD

**Issue by Kogasa-touhou** [WearBlackAllDay/DimensionalThreading#33]
My 1.17.1 fabric server may let player‘s client get stuck.
I tried to use spark .
Here is the result.
https://spark.lucko.me/RQ4qMXBwqM

![image](https://user-images.githubusercontent.com/67717065/125153174-80eed300-e184-11eb-97bd-889bb6293fe5.png)

**Comment by WearBlackAllDay** [comment]
to conserve vanilla parity the game will always run at the pace of the slowest dimension.
this means if one dim is significantly slower than the others the 2 other threads spend alot of time waiting.

**Comment by WearBlackAllDay** [comment]
`may let player‘s client get stuck`
mind explaining what you mean here?
i cant make any sense of this
dimthread is a server-mod so i dont see how a client would get "stuck"
