### ISSUE TITLE
Crash when trying to use /schedule command

### ISSUE THREAD

**Issue by Devon7925** [WearBlackAllDay/DimensionalThreading#4]
Here we go again with another crash report. Using the /schedule command will freeze the server until it crashes due to a tick taking too long.

**Comment by KaptainWutax** [comment]
Could you provide the command you ran and the crash report?

**Comment by Devon7925** [comment]
command was `schedule function _insert function name from datapack here_ 1t`
This https://pastebin.com/PsJcYqkW is probably the correct crash report, idk it crashed a lot. Plus the crash isn't caused by the command directly but rather from the server timing out due to the server being frozen.

**Comment by KaptainWutax** [comment]
I don't know much about datapacks sadly but that looks to me like a dimension is requesting chunks from another one and deadlocking? Something like that... I'll look into it.
