### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by Devon7925** [WearBlackAllDay/DimensionalThreading#5]
This isn't a new issue but I decided to catch it on video [here](https://youtu.be/5w4aMyHjTlM). Not sure if it matters but it was in a custom dimension.

**Comment by Devon7925** [comment]
I also have carpet and lithium installed

**Comment by KaptainWutax** [comment]
You're using v1.2 right? And could I get the watchdog crash report? :p

**Comment by Devon7925** [comment]
yes, I am using 1.2. not sure how to get a crash report since there is no crash

**Comment by KaptainWutax** [comment]
So you're in singleplayer then? Sadly there's no watchdog crash in SP.

**Comment by Devon7925** [comment]
No im on a multiplayer server, there just is no crash so there is no crash report

**Comment by KaptainWutax** [comment]
Then I don't understand what the problem is.

**Comment by Devon7925** [comment]
Its pretty clear if you watch the video... caterpillar engines are randomly stopping

**Comment by KaptainWutax** [comment]
I was under the impression that it was a server hangup? Well, I really don't see how it could affect redstone at all. Are you sure it only happens with dimthread on? I'll be doing testing myself.

**Comment by Devon7925** [comment]
I've only observed it with dim thread on, and my use case involves a lot of flying machines so I experience this a lot.

**Comment by KaptainWutax** [comment]
I have not been able to reproduce this.
