### ISSUE TITLE
Publish DimensionalThreading to Cursefoge/Modrinth

### ISSUE THREAD

**Issue by luni3359** [WearBlackAllDay/DimensionalThreading#62]

**Comment by LiviiYS** [comment]
I agree, would love to add it to my Modpack so I'd also love for it to be added to curseforge.

**Comment by WearBlackAllDay** [comment]
https://modrinth.com/mod/dimthread

**Comment by luni3359** [comment]
Thank you so much, I really appreciate it!!! ❤️
