### ISSUE TITLE
Unable to start server with Bukkit4Fabric installed

### ISSUE THREAD

**Issue by Blobanium** [WearBlackAllDay/DimensionalThreading#8]
hi so the server fails to start when i try to use Bukkit4Fabric and your mod, the server crashes when i try to start it up.
Mods
![Capture](https://user-images.githubusercontent.com/45613796/101105828-6a93ef80-3583-11eb-9df5-e0aa20e107d0.PNG)

Crash log
[crash-2020-12-03_15.24.04-server.txt](https://github.com/WearBlackAllDay/DimensionalThreading/files/5639819/crash-2020-12-03_15.24.04-server.txt)

tell me if there's anything else i need

**Comment by WearBlackAllDay** [comment]
The codebase of Bukkit4Fabric currently makes compatibility impossible. Unless the B4F author adjusts their code, the two mods will not be compatible. (Using the vanilla Server object)

**Comment by Blobanium** [comment]
ok so the creator has adjusted their code to be compatible with Cardboard/Bukkit4Fabric as of build 149, probably no longer needs to be open
