### ISSUE TITLE
1.20 in the future?

### ISSUE THREAD

**Issue by Jayspek** [WearBlackAllDay/DimensionalThreading#86]
Just curious if there is a 1.20 version planned/in the works, as the current version causes the game to crash.

**Comment by allanonmage** [comment]
Looks like there hasn't been an update in a while, so maybe this is abandoned?

**Comment by WearBlackAllDay** [comment]
This project was originally summoned to bring and old project from [2No2Name](https://github.com/2No2Name) back to modern versions of mc.
As per 1.19 he has choosen to [continue](https://github.com/2No2Name/worldthreader) the project, thus making this repo obsolete. 
Should he at any point quit again, i will continue this repo, but until then, yes, you can consider this abandoned in favor of his repo.

**Comment by ShiftySpace** [comment]
Thank you very much for the info on world threader. Very happy there is a mod for 1.20 that makes this possible :)

**Comment by 13Ralef** [comment]
How's the mod of 2No2Name called? What's the mod? I wanna try it

**Comment by Jayspek** [comment]
https://github.com/2No2Name/worldthreader/tree/mc1.20-1.5.0

It's only for 1.20 unfortunately. My understanding is if you change the version in the mod info file it will work in 1.20.1 as well, but it won't run on 1.20.4.

**Comment by xZx-X-xZx** [comment]
> https://github.com/2No2Name/worldthreader/tree/mc1.20-1.5.0
> 
> It's only for 1.20 unfortunately. My understanding is if you change the version in the mod info file it will work in 1.20.1 as well, but it won't run on 1.20.4.

The version number in fabric.mod.json has been modified to 1.20.1. The server can run, but the logs keep repeating. It is also unclear whether the module is effective.

![image](https://github.com/WearBlackAllDay/DimensionalThreading/assets/54734776/d8cc12d3-2673-42a8-9e5d-f15338e3e49a)
